---
name: "EDS 212: Day 1 Activity"
author: "Takeen Shamloo"
editor_options: 
  chunk_output_type: console
---

```{r}
# Load packages ----
library(tidyverse)
library(janitor)
```

## Reading in data ----

```{r}
stl_lead <- read.csv(here::here("data", "stl_blood_lead.csv"))
stl_lead <- stl_lead |> clean_names() # Cleaning names to lower_snake_case
```

## Basic exploration ----
```{r}
names(stl_lead) # List all column names
dim(stl_lead) # Gives dimensions
skimr::skim(stl_lead) # Show some summary statistics
```

## Add a column ----
```{r}
stl_lead_prop <- stl_lead
stl_lead_prop$prop_white <- (stl_lead_prop$white / stl_lead_prop$total_pop) * 100
```

## Scatter Plot ----

```{r}
stl_lead_plot <- ggplot(stl_lead_prop, aes(x = prop_white, y = pct_elevated)) + 
  geom_point(aes(color = prop_white), show.legend = FALSE) + 
  theme_minimal() +
  scale_color_gradient(low = "green", high = "red") +
  labs(title = "Blood lead propotions in white children",
      x = "% of each census tract identifying as white",
      y = "% of children with elevated blood lead")

stl_lead_plot
```

Counties with a higher proportion of white people have less lead within their blood stream.

## Export a scatterplot ----

```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```

## Histogram ----

```{r}
stl_lead_histogram <- ggplot(stl_lead_prop, 
                             aes(x = pct_elevated)) +
  geom_histogram(aes(fill = "maroon")) +
  labs(title = "Children at different lead %'s", 
       x = "% of children with elevated blood lead",
       y = "Count")

stl_lead_histogram
```

## Export a histogram ----

```{r}
ggsave(here::here("figs", "stl_lead_histogram.jpg"), height = 6, width = 5)
```


